name: Build and Publish Remote-Vector-Index-Builder Snapshot

on:
  push:
    branches:
      - main
      - github-ci

permissions:
  contents: read

jobs:
  build-and-publish-snapshot:
    name: Build and Publish Remote-Vector-Index-Builder Snaphot Image
    runs-on: [self-hosted, remote-vector-g62xlarge, gpu, X64, Linux]

    steps:
      # https://github.com/actions/checkout?tab=readme-ov-file#usage
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
      
      - name: Build Docker Image
        run : |
            docker build  -f ./base_image/build_scripts/Dockerfile . -t opensearchstaging/remote-vector-index-builder:base-1.0.0
            docker tag opensearchstaging/remote-vector-index-builder:base-1.0.0 opensearchstaging/remote-vector-index-builder:base-latest
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.REMOTE_VECTOR_DOCKER_ROLE }}
            aws-region: us-east-1
      
      - name: Retrieve Values
        id: retrieve-values
        run: |
            DOCKERHUB_PASSWORD=`aws secretsmanager get-secret-value --secret-id jenkins-staging-dockerhub-credential --query SecretString --output text`
            echo "::add-mask::$DOCKERHUB_PASSWORD"
            echo "dockerhub-password=$DOCKERHUB_PASSWORD" >> $GITHUB_OUTPUT
          
        # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
            password: ${{ steps.retrieve-values.outputs.dockerhub-password }}
    
      - name: Push Docker Image
        run : |
            docker push opensearchstaging/remote-vector-index-builder:base-1.0.0
            docker push opensearchstaging/remote-vector-index-builder:base-latest

      # Standard Step
      - name: Logout to DockerHub
        if: always()
        run: docker logout