name: Build and Publish Remote-Vector-Index-Builder Faiss Base Image to Docker

on:
  pull_request:
    branches:
      - faiss_base_image
    paths:
        - 'base_image/**'
        - '.github/workflows/publish_faiss_base_image.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-faiss-base-image:
    name: Build and Publish Remote-Vector-Index-Builder Faiss Base Image
    if: github.repository == 'opensearch-project/remote-vector-index-builder'
    runs-on:
      group: selfhosted-gpu-runners
      labels: g62xlarge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'

      - name: Build Docker Image
        run : |
            docker build  -f ./base_image/build_scripts/Dockerfile . -t opensearchstaging/remote-vector-index-builder:faiss-base-1.0.0
            docker tag opensearchstaging/remote-vector-index-builder:faiss-base-1.0.0 opensearchstaging/remote-vector-index-builder:faiss-base-latest

      # Add Trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'opensearchstaging/remote-vector-index-builder:faiss-base-1.0.0'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          timeout: '10m'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.REMOTE_VECTOR_DOCKER_ROLE }}
            aws-region: us-east-1

      - name: Retrieve Values
        id: retrieve-values
        run: |
            DOCKERHUB_PASSWORD=`aws secretsmanager get-secret-value --secret-id jenkins-staging-dockerhub-credential --query SecretString --output text`
            echo "::add-mask::$DOCKERHUB_PASSWORD"
            echo "dockerhub-password=$DOCKERHUB_PASSWORD" >> $GITHUB_OUTPUT
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
            password: ${{ steps.retrieve-values.outputs.dockerhub-password }}

      - name: Runner Cleanups
        if: always()
        run: |
          docker logout
          docker system prune -a -f
          rm -rf ${{ github.workspace }}/*